### PR TITLE
PR for #25 - UWP system.io.file.exsts fixes

### PR DESCRIPTION
**Pull request by jasells**
This works as expected on UWP.

### CODE REVIEW

**Comment by jasells** [comment]
@jamesmcroft ,

I hope all is well.  I was wondering if you had a chance to take a look at this?  I would like to move ahead, but not sure if you're thinking of accepting this PR, or what...?

**Comment by jamesmcroft** [comment]
@jasells apologies, I have been on holiday recently and haven't been as active online. I'll give this a review now.

**Comment by jamesmcroft** [comment]
Related - #25

**Comment by jamesmcroft** [comment]
More than happy with this fix. Will get a new NuGet package out ASAP

**Pull request merged**
